export const lightRed = '#f77a7a'
export const lightGray = '#eaeaea'
export const darkGray = '#4c4b4b'
export const black = '#484848'
export const yellow = '#ffc800'
export const lightGreen = '#9dbf4e'
export const white = '#ffffff'
